# Data Configuration
data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  dataset_name: "movielens"
  movie: "data/raw/movies.dat"
  ratings: "data/raw/ratings.dat"
  users: "data/raw/users.dat"
  train: "data/processed/train.csv"
  test: "data/processed/test.csv"
  db: "data/processed/cineSense.db"
  dataset_path: "data/processed/movie_dataset.csv"


# Retrieval Model Settings
retrieval:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  vector_store: "faiss"
  top_k: 10

# Reinforcement Learning Agent Settings
reinforcement_learning:
  model_type: "DQN"
  gamma: 0.99
  learning_rate: 0.001
  batch_size: 64
  replay_buffer_size: 10000
  training_episodes: 1000

# API Configuration
api:
  host: "0.0.0.0"
  port: 8080
  url: "http://127.0.0.1:8000"

# UI Configuration
ui:
  theme: "dark"

# Pinecone configuration
pinecone:
  index_name: "cinesense"
  dimension: "384"
  metric: "cosine"



